#!/usr/bin/env python
logfile = open('tedu_access.log1')
log_list = logfile.readlines()
logfile.close()
log_dict = {}
re_dict = {}
log_sort = []
end_log = []
for log_line in log_list:
    line_list = log_line.split(' ')
    line_tuple = (line_list[8],line_list[6],line_list[0])
    if line_tuple in log_dict:
        log_dict[line_tuple] += 1
    else:
        log_dict[line_tuple] = 1

for k in log_dict:
    re_k = log_dict[k]
    re_v = k
    if re_dict.has_key(re_k):
        if type(re_dict[re_k]) == type([]):
             re_dict[re_k].append(re_v)
        else:
            tmp = re_dict[re_k]
            re_dict[re_k] = []
            re_dict[re_k].append(tmp)
            re_dict[re_k].append(re_v)
    else:
        re_dict[re_k] = re_v

for key in re_dict:
    log_sort.append(key)

log_sort.sort()

for num in log_sort[:10]:
    print re_dict[num]
