#!/usr/bin/env python
max = 0
sec = 0
list = [1,2,3,2,12,3,1,3,21,2,2,3,4111,22,3333,444,111,4,5,777,65555,45,33,45]
for i in list:
    if i > max:
       max  = i
for j in list:
    if j > sec:
       tmp = j
       if tmp == max:
           continue
       sec = tmp
print "THE MAX IS %s" %(max)
print "THE SECOND IS %s" %(sec)
